version: 2.1

jobs:
  tracking-car:
    docker:
      - image: 'traccar/traccar:latest'
    steps:
      
      - kubernetes/install-kubectl
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: manifestos
          resource-name: deployment/traking-car
          show-kubectl-command: true



    
